services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'remind_me_db'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  my-db:
