services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'remind_me_db'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
volumes:
  my-db:
