services:
  db:
    image: mysql:latest
    restart: always
    environment:
      DB_USER: 'root'
      DB_PASSWORD: 'password'
      DB_NAME: 'remind_me_db'
      DB_PORT: 3306
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: